ci: update client ci

diff --git a/.github/workflows/client-ci.yml b/.github/workflows/client-ci.yml
--- a/.github/workflows/client-ci.yml
+++ b/.github/workflows/client-ci.yml
@@ -6,6 +6,10 @@ on:
   pull_request:
     paths:
       - 'client/**' # only run if something in client/ changes
+  workflow_dispatch:
+
+env:
+  NODE_VERSION: "20"
 
 jobs:
   lint:
@@ -17,7 +21,7 @@ jobs:
       - name: Setup Node 
         uses: actions/setup-node@v4
         with:
-          node-version: 20
+          node-version: ${{ env.NODE_VERSION }}
           cache: npm
           cache-dependency-path: client/package-lock.json
 
@@ -29,36 +33,10 @@ jobs:
         working-directory: client
         run: npx eslint src src-electron
 
-  test-build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Setup Node 
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: npm
-          cache-dependency-path: |
-            schema/package-lock.json
-            client/package-lock.json
-
-      - name: Install schema dependencies
-        working-directory: ./schema
-        run: npm ci
-
-      - name: Install dependencies
-        working-directory: client
-        run: npm ci
-
-      - name: Test build
-        working-directory: client
-        run: npm run build:pack
-
   release-please:
-    runs-on: ubuntu-latest
     if: ${{ !failure() && github.ref == 'refs/heads/main' }}
+    runs-on: ubuntu-latest
+    needs: lint
     permissions:
       contents: write
       pull-requests: write
@@ -70,20 +48,6 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Configure release-please
-        id: release-config
-        run: |
-          if [ -f .github/release-please-config.json ]; then
-            echo "config-file=.github/release-please-config.json" >> $GITHUB_OUTPUT
-            [ -f .github/release-please-manifest.json ] &&
-              echo "manifest-file=.github/release-please-manifest.json" >> $GITHUB_OUTPUT
-            [ -f .github/.release-please-manifest.json ] &&
-              echo "manifest-file=.github/.release-please-manifest.json" >> $GITHUB_OUTPUT
-          else
-            echo "release-type=node" >> $GITHUB_OUTPUT
-          fi
-          exit 0
-
       - name: Release
         uses: googleapis/release-please-action@v4
         id: release
@@ -92,28 +56,38 @@ jobs:
           release-type: ${{ steps.release-config.outputs.release-type }}
           manifest-file: ${{ steps.release-config.outputs.manifest-file }}
 
+      - name: Create Release
+        uses: googleapis/release-please-action@v4
+        id: release
+        with:
+          config-file: ${{ hashFiles('.github/release-please-config.json') != '' && '.github/release-please-config.json' || '' }}
+          manifest-file: ${{ hashFiles('.github/release-please-manifest.json') != '' && '.github/release-please-manifest.json' || hashFiles('.github/.release-please-manifest.json') != '' && '.github/.release-please-manifest.json' || '' }}
+          release-type: node
+
       - name: Debug release
         continue-on-error: true
         run: |
           echo "${{ toJSON(steps.release.outputs) }}"
 
   build:
+    if: ${{ !failure() && (github.ref == 'refs/heads/main' || github.base_ref == "main") }}
+    needs: [lint, release-please]
     strategy:
       matrix:
         include:
           - os: macos-latest
-            platform: mac
-          - os: ubuntu-22.04
+            platform: darwin
+            artifact-name: mac-client
+            extension: app
+          - os: ubuntu-latest
             platform: linux
+            artifact-name: linux-client
+            extension: AppImage
           - os: windows-latest
             platform: win
+            artifact-name: windows-client
+            extension: exe
     runs-on: ${{ matrix.os }}
-    needs: [test-build, release-please]
-    if: ${{ !failure() && github.ref == 'refs/heads/main' && needs.release-please.outputs.releases_created == 'true' }}
-    env:
-      NODE_VERSION: "20"
-      WORKING_DIR: ./client
-      ARTIFACT_PATH: "./packed-client/${{ matrix.path }}"
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -128,35 +102,66 @@ jobs:
             client/package-lock.json
 
       - name: Install schema dependencies
-        working-directory: ./schema
+        working-directory: schema
         run: npm ci
 
       - name: Install client dependencies
-        working-directory: ${{ env.WORKING_DIR }}
+        working-directory: client 
         run: npm ci
 
       - name: Build app
-        working-directory: ${{ env.WORKING_DIR }}
-        shell: bash
+        working-directory: client 
         run: npm run build:pack
 
-      - name: Prepare zips
-        working-directory: ${{ env.WORKING_DIR }}
-        run: 7z a -tzip packed-client/${{ matrix.platform }}-client.zip ${{ env.ARTIFACT_PATH }}
+      - name: List top-level releases folder
+        working-directory: client
+        shell: bash
+        run: |
+          echo "Top-level releases folders:"
+          ls -1 releases
 
+      - name: Check build output
+        id: check-build
+        working-directory: client
+        shell: bash
+        run: |
+          if [ -d "releases/${{ matrix.platform }}" ] && [ "$(ls -A releases/${{ matrix.platform }})" ]; then
+            echo "has-builds=true" >> $GITHUB_OUTPUT
+          else
+            echo "has-builds=false" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+
+      - name: Prepare zips
+        if: ${{ needs.release-please.outputs.releases_created == 'true' }}
+        working-directory: client 
+        shell: bash
+        run: |
+          mkdir -p release-assets
+
+          ARTIFACT_PATH=$(find releases -maxdepth 3 -name "*${{ matrix.extension }}" | head -n 1)
+
+          if [[ -z "$ARTIFACT_PATH" ]]; then
+            echo "Error: no artifact found for extension ${{ matrix.extension }}"
+            exit 1
+          fi
+
+          echo "Zipping $ARTIFACT_PATH into release-assets/${{ matrix.artifact-name }}.zip"
+          7z a -tzip release-assets/${{ matrix.artifact-name }}.zip "$ARTIFACT_PATH"
 
       - name: Upload built client as artifact
+        if: ${{ needs.release-please.outputs.releases_created == 'true' }}
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ matrix.platform }}-client
+          name: ${{ matrix.artifact-name }}
           path: |
-            ${{ env.WORKING_DIR }}/packed-client/*-client.zip
+            client/release-assets/${{ matrix.artifact-name }}.zip
           if-no-files-found: error
 
-  release:
+  publish:
+    if: ${{ !failure() && github.ref == 'refs/heads/main' && needs.release-please.outputs.releases_created == 'true' }}
     needs: [build, release-please] 
     runs-on: ubuntu-latest
-    if: ${{ !failure() && github.ref == 'refs/heads/main' && needs.release-please.outputs.releases_created == 'true' }}
     permissions:
       contents: write
     steps:
@@ -166,16 +171,19 @@ jobs:
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
-          path: ./artifacts/
+          path: ./release-assets/
+
+      - name: List artifacts
+        run: find ./release-assets -type f -ls
 
       - name: Upload assets to GitHub Release
         uses: svenstaro/upload-release-action@v2
         with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: artifacts/**/*.zip
+          file: release-assets/**/*.zip
           file_glob: true
           tag: ${{ needs.release-please.outputs.tag_name }}
-          release_name: "Client Release ${{ needs.release-please.outputs.tag_name }}"
+          release_name: "Client ${{ needs.release-please.outputs.tag_name }}"
           overwrite: true
           make_latest: true
 
